name: App deployment on kubernetes
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image and push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ttyeri/myweather:V1
  deploy:
     name: Init kube cluster
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Install kubectl
         uses: azure/setup-kubectl@v3
       - name: Setup kubeconfig
         run: |
             mkdir ${HOME}/.kube
             echo ${{secrets.KUBECONFIG_CICD}} | base64 -d > ${HOME}/.kube/config
             echo ${HOME}/.kube/config
       - name: Setup context
         run: |
             kubectl config use-context cicd-sa-ctx
       - name: Check node / pods
         run: |
             kubectl get node
             kubectl get pod
